### ISSUE TITLE
ReloadFail: Bootstrap not executable

### ISSUE THREAD

**Issue by zhuangdx** [second-state/tencent-tensorflow-scf#1]
clone代码后，部署云函数，网页传图片识别结果返回
{"errorCode":-1,"errorMessage":"ReloadFail: Bootstrap not executable\n","statusCode":443}

**Comment by zhuangdx** [comment]
应该是windows下clone后，二进制的权限丢失，我在linux试下

**Comment by gnefix** [comment]
> clone代码后，部署云函数，网页传图片识别结果返回
> {"errorCode":-1,"errorMessage":"ReloadFail: Bootstrap not executable\n","statusCode":443}

同样的情况

**Comment by zhuangdx** [comment]
centos,
![image](https://user-images.githubusercontent.com/16098983/105973382-a2bd3780-60c7-11eb-91cc-3cd5915b6c37.png)

**Comment by zhuangdx** [comment]
用https://blog.csdn.net/weixin_42376823/article/details/113260427

**Comment by zhuangdx** [comment]
sls提示login是因为.env替换了自己的密钥，需要有原代码的其他参数
![image](https://user-images.githubusercontent.com/16098983/105977866-d77fbd80-60cc-11eb-85d9-339e484ac649.png)
