### ISSUE TITLE
release接口 Bootstrap not executable

### ISSUE THREAD

**Issue by zhang156** [second-state/tencent-tensorflow-scf#3]
仓库: 从本仓库fork出来的

部署: win32 docker, 镜像用的 secondstate/tencent-tensorflow-scf

复现流程:  上传图片点击 "这是什么食物"

![image](https://user-images.githubusercontent.com/24284204/107172199-b3db4200-69ff-11eb-98bd-7b2c726d2f0b.png)

**Comment by alabulei1** [comment]
Hi, please refer to this article
https://blog.csdn.net/weixin_42376823/article/details/113260427

**Comment by zhang156** [comment]
thx @alabulei1
